authors:
  Yasmin:
    name: Yasmin
    description: AI Safety Advocate
    avatar: https://github.com/Yasmin-FY.png
    url: https://github.com/Yasmin-FY
  Scott:
    name: Scott
    description: Software developer, security engineer, and author
    avatar: https://github.com/ynori7.png
    url: https://github.com/ynori7